# main menu navigation url and icon
menu:
  Tools:
    url: /imotools
    icon: fa-cog
  Tags:
    url: /tags
    icon: fa-tags
  Categories:
    url: /categories
    icon: fa-bookmark
  About:
    url: /about
    icon: fa-info-circle
  My Friends:
    url: /friends
    icon: fa-user-secret
# Index cover carousel configuration.
cover:
  showPrevNext: true # Whether to display the left and right toggle buttons.
  showIndicators: true # Whether to display the indicators
  autoLoop: true # Whether it is automatically rotated.
  duration: 120 # Switching delay time.
  intervalTime: 5000 # Automatically switch the interval of the next one.

# index page dream text,
dream:
  enable: true
  showTitle: true
  title: Blog Guide
  text: Blog ini ditujukan buat Anda yang suka mengeksplor hal baru terutama Dunia Online karena disini akan membahas seputar tips, trick dan tutorial yang akan sangat bermanfaat. Untuk memudahkan pencarian pada blog ini silahkan akses kategori atau pembahasan yang Anda inginkan lewat menu navigasi

# Whether to display the title of the recommended posts
recommend:
  showTitle: true

# Configure website favicon and LOGO
favicon: /digimoclub.png
logo: /medias/keymetrics.svg

# The configuration of the second button in the home banner,
# including the display name of the button, the font awesome icon, and the hyperlink to the button.
indexbtn:
  enable: true
  name: FREE TOOLS
  icon: fa-home
  url: https://www.digimoclub.com/imotools

# The configurations of the second line of home banner
# icon/button will not show up if you leave the corresponding socialLink empty
socialLink:
  qq: imoclub
  github: digimoclub
  email: imoclubonline

# Whether to activate the Post TOC, and Configure which title types are supported by TOC support.
# You can add `toc: false` to the Front-matter of a post to turn off the TOC.
toc:
  enable: true
  heading: h2, h3, h4

# Whether the code is broken.
code:
  break: true

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: true
  title: Hi Guys!!!
  wechat: /medias/reward/facebook.svg
  alipay: /medias/reward/telegram.svg

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: false
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# Whether to activate the mathjax, this is a global configuration, but the post still does not open the mathjax rendering.
# Considering that the mathjax loading is time consuming,
# you also need to add `mathjax: true` to the Front-matter of the post that needs to be rendered.
# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Post word count, reading duration, site total word count.
# Before you activate, please confirm that you have installed the hexo-wordcount plugin,
# install the plugin command: `npm i --save hexo-wordcount`.
# 文章字数统计、阅读时长、总字数统计
# 激活前请确认你已经安装了 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true

# profile in about page, including avatars, career, and personal introductions.
# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: /medias/avatar.jpg
  career: Web Develepor & Digital Marketer
  introduction: Seorang otodidak dengan predikat terbaik sebagai "Ayah" yang sengaja mencemplungkan Diri ke dunia programming yang akhirnya membuat quote singkat (-- "Berani mencoba lebih baik dari pada menyerah saat membayangkan" --)

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: false
  data:
    IMO Landing Theme:
      icon: fa-wordpress
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: https://t.me/imoclub
      desc: Theme Premium Wordpress untuk segala fungsi dan sangat cocok untuk pebisnis online
    IMO Icon Theme:
        icon: fa-wordpress
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://t.me/imoclub
        desc: Theme Premium Wordpress yang di desain khusus untuk blogger yang fokus dengan SEO atau Traffic Paid
    IMO Dropship:
        icon: fa-connectdevelop
        iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
        url: https://t.me/imoclub
        desc: Source Code untuk mendapatkan app web seperti tools droship yang ada di menu navigasi blog ini

# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    Java:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 85%
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 80%
    HTML5:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 80%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 70%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 90%
    PHP:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 75%

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: false
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

# disqus config, default disabled
# Disqus评论模块的配置，默认为不激活
disqus:
  enable: true
  shortname: digimoclub

# Whether to display fork me on github icon and link, default true, You can change it to your repo address
# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: false
  url: https://github.com/blinkfox/hexo-theme-matery
  title: Fork Me


# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: true
  id: UA-133582811-1

# The used front-end library can be replaced with the corresponding CDN address as needed,
# If the specific version is not specified below, you can use the latest version.
# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css:
    fontAwesome: https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css # V4.7.0
    materialize: https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css # 1.0.0
    aos: https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css
    animate: https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.6.11
    jqcloud: https://cdnjs.cloudflare.com/ajax/libs/jqcloud/1.0.4/jqcloud.css
    googlefont: https://fonts.googleapis.com/css?family=Open+Sans
  js:
    jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
    materialize: https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js
    scrollProgress: https://cdnjs.cloudflare.com/ajax/libs/scrollprogress/3.0.2/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.6.11
    busuanzi: /libs/others/busuanzi.pure.mini.js
    echarts: https://cdnjs.cloudflare.com/ajax/libs/echarts/4.2.1/echarts.min.js
    jqcloud: https://cdnjs.cloudflare.com/ajax/libs/jqcloud/1.0.4/jqcloud-1.0.4.min.js

# The post featured images that needs to be displayed when there is no image.
# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- /medias/featureimages/thumb.jpg
