posts: Posts
category: Category
categories: Categories
tag: Tag
tags: Tags
archives: Archives
about: About
friends: Friends
startRead: Start
recommendedPosts: Recommended Posts
publishDate: Publish Date
readCount: Read Count
wordCount: Word Count
readTimes: Read Times
Minutes: Min
readMore: Read more
toc: Daftar isi
reprint: Walking From
curr: Current
prev: Previous
next: Next
search: Search
searchTip: Please enter a search keyword
postTagTitle: Post Tags
postCategoryTitle: Post Categories
categoryRadarTitle: Post Categories Radar Chart
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: Post Charts
postPublishChart: Post Publish Chart
categoriesChart: Categories Chart
top10TagsChart: TOP10 Tags Chart
postsNumberName: Number of posts
maximum: Maximum
minimum: Minimum
average: Average
myProjects: FREEMIUM GIFT
mySkills: My Skills
otherSkills: Blog Library
gallery: Gallery
from: From
author: Author
link: Link
notag: No tag